# -*- makefile -*-

# adding variables
include ../make.vars

all:

install:
	mkdir -p $$DESTDIR$(MAN_DIR)/man5 $$DESTDIR$(MAN_DIR)/man8
	cp lilo.8 $$DESTDIR$(MAN_DIR)/man8
	cp mkrescue.8 $$DESTDIR$(MAN_DIR)/man8
	cp lilo.conf.5 $$DESTDIR$(MAN_DIR)/man5
	cp keytab-lilo.8 $$DESTDIR$(MAN_DIR)/man8

clean:

distclean:

