# -*- makefile -*-

# adding variables
include ../make.vars

all:

install:
	mkdir -p $$ROOT$(MAN_DIR)/man5 $$ROOT$(MAN_DIR)/man8
	cp lilo.8 $$ROOT$(MAN_DIR)/man8
	cp mkrescue.8 $$ROOT$(MAN_DIR)/man8
	cp lilo.conf.5 $$ROOT$(MAN_DIR)/man5

clean:

distclean:

